#!/system/bin/sh
#
# bind mount /data/local/download to /cache/download if cache
# partition is too small
#

CACHESIZE=$(df -k /cache | tail -n1 | tr -s ' ' | cut -d ' ' -f2)
DATAONLY=$(getprop dalvik.vm.dexopt-data-only)
if [ "$DATAONLY" = "1" ]
then
  NEEDED=60000
else
  NEEDED=105000
fi

CACHEONLY=$(getprop dalvik.vm.dexopt-cache-only)
if [ $CACHEONLY -eq 1 ]
then
  NEEDED=150000
fi

if [ $CACHESIZE -lt $NEEDED ]
then
  mount -o bind /data/local/download /cache/download
fi

rm /cache/download/downloadfile*.apk >/dev/null 2>&1

exit 0
